kind = "web"
previewPath = "/"
title = "Toko Militer Indonesia"
version = "1.0.0"
id = "artifacts/militer-store"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22796

[services.development]
run = "pnpm --filter @workspace/militer-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/militer-store", "run", "build" ]
publicDir = "artifacts/militer-store/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22796"
BASE_PATH = "/"
